language: java
jdk:
  - openjdk8


install: ant

script:
  - ant test
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - manuelsturla@gmail.com
      - diego.balestieri1998@gmail.com
      - Santiagolampropulos@gmail.com
      - flia_giampietri@yahoo.com
    on_failure: always
